---
default_set: 'centos-64-x64'
sets:
  'centos-64-x64':
    nodes:
      'main.vm':
        prefab: 'centos-64-x64'
  'centos-59-x64':
    nodes:
      'main.vm':
        prefab: 'centos-59-x64'
  'fedora-18-x64':
    nodes:
      'main.vm':
        prefab: 'fedora-18-x64'